# Generated by Django 2.1.7 on 2019-04-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20190331_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_file',
            field=models.FileField(default=1, upload_to=''),
        ),
    ]
